FROM python:3.11-slim

WORKDIR /app

RUN pip install pyyaml
RUN pip install torch==2.1.0 --index-url https://download.pytorch.org/whl/cpu
RUN pip install torchvision==0.16.0 --index-url https://download.pytorch.org/whl/cpu

COPY training_job/ .

CMD ["python3", "train.py"]
