FROM python:3.11-slim

WORKDIR /app
RUN pip install pyyaml
RUN pip install "numpy<2"
RUN pip install torch==2.1.0 --index-url https://download.pytorch.org/whl/cpu
RUN pip install torchvision==0.16.0 --index-url https://download.pytorch.org/whl/cpu
RUN pip install fastapi uvicorn
COPY training_job/ .
CMD ["sh", "-c", "uvicorn server:app --host 0.0.0.0 --port 8001 & python3 train.py"]
